name: multithreading_image_processor
description: A sample command-line application.
version: 1.8.0

environment:
  sdk: ^3.0.0

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
dependencies:
  color: ^3.0.0
  dotenv: ^4.1.0
  http: ^0.13.5
  image: ^4.0.15
  mime: ^1.0.4
  nyxx: ^5.0.3
  nyxx_commands: ^5.0.2

assets:
  - .env
